import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { title, tagLine } from "./common";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const menuitems = [
  {
    title: "Home",
    path: "/",
  },
  {
    title: "About",
    path: "/about",
  },
  {
    title: "Members",
    path: "/members",
  },
  {
    title: "Code of Conduct",
    path: "/code-of-conduct"
  }

];



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html>
      <body className="bg-slate-100 space-y-10">

        <header className="flex items-center justify-between p-6  border-b bg-gray-100">
          <div className="text-xl font-bold">{title}</div>
          <nav>
            {
              menuitems.map((item, index) => (

                <a key={index} href={item.path} className="ml-4 hover:underline">{item.title}</a>
              ))}
          </nav>

        </header>

        <main className="flex flex-col items-center justify-center py-2">
          <div className="w-9/12">
            {children}
          </div>
        </main>
        <footer className="flex flex-col items-center justify-center w-full h-24 border-t bg-gray-100 text-gray-500">
          <div className="mt-2">
            <a href="https://twitter.com" className="mx-2 hover:text-blue-600">Twitter</a>
            <a href="https://linkedin.com" className="mx-2 hover:text-blue-600">LinkedIn</a>
          </div>
          <p className="text-center text-sm">
            &copy; {new Date().getFullYear()} {title}. All rights reserved.
          </p>
        </footer>

      </body>
    </html>
  )
}
